version: '3.8'

services:
  react-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production   # ya development, jo chahiye wo rakho
    volumes:
      - .:/app
      - /app/node_modules
    labels:
      - subdomain=if.workbrink.com
      - websiteName=itec-frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002"]
      interval: 30s
      timeout: 10s
      retries: 3

